### ISSUE TITLE
Calendar.DateTime can't be used directly in queries

### ISSUE THREAD

**Issue by stevedomin** [lau/calecto#18]
The following code fails because you can't use DateTime struct directly in queries:

``` elixir
 def all_users() do
    now = Calendar.DateTime.now_utc |> Calecto.DateTimeUTC.cast
    from(u in Eager.User,
      where: fragment("(?).wall_time > ?", u.start_datetime, ^now),
      select: u)
  end
```

``` elixir
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.DateTime.encode_timestamp/1
        (ecto) lib/ecto/adapters/postgres/datetime.ex:47: Ecto.Adapters.Postgres.DateTime.encode_timestamp(%Calendar.DateTime{abbr: "UTC", day: 3, hour: 23, min: 53, month: 2, sec: 58, std_off: 0, timezone: "Etc/UTC", usec: 687669, utc_off: 0, year: 2016})
        (postgrex) lib/postgrex/query.ex:90: DBConnection.Query.Postgrex.Query.do_encode/3
        (postgrex) lib/postgrex/query.ex:51: DBConnection.Query.Postgrex.Query.encode/3
        (db_connection) lib/db_connection.ex:885: DBConnection.describe_execute/5
        (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
        (db_connection) lib/db_connection.ex:421: DBConnection.query/4
        (postgrex) lib/postgrex.ex:105: Postgrex.query/4
        (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
        (stdlib) timer.erl:197: :timer.tc/3
        (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.query/7
        (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
        (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
        (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
        (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:481: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
```

**Comment by lau** [comment]
It looks like changes are needed in Ecto. Because it is a composite type. Calendar structs should work directly with the other field types.

Until Ecto is changed, it is necessary to convert the DateTime structs to "micro_erl" tupples with DateTime.micro_erl e.g. `DateTime.now_utc |> DateTime.to_micro_erl`

**Comment by josevalim** [comment]
@stevedomin can you please try the following:

```
where: fragment("(?).wall_time > ?", type(u.start_datetime, :datetime), type(^now, :datetime))
```

If it doesn't work, please try `Ecto.DateTime` instead of `:datetime`.

**Comment by stevedomin** [comment]
@josevalim 

``` elixir
def upcoming_events(group) do
  now = Calendar.DateTime.now_utc |> Calecto.DateTimeUTC.cast
  #now = Calendar.DateTime.now_utc |> Calendar.DateTime.to_micro_erl
  from(g in Eager.Group,
    join: e in assoc(g, :events),
    where: e.group_id == ^group.id,
    where: fragment("(?).wall_time > ?", type(e.start_datetime, :datetime), type(^now, :datetime)),
    #where: fragment("(?).wall_time > ?", e.start_datetime, ^now),
    select: e)
end

# error
** (Ecto.Query.CompileError) `type(e.start_datetime(), :datetime)` is not a valid query expression.

* If you intended to call a database function, please check the documentation
  for Ecto.Query to see the supported database expressions

* If you intended to call an Elixir function or introduce a value,
  you need to explicitly interpolate it with ^
```

Same error with `Ecto.DateTime`

**Comment by josevalim** [comment]
Sorry, you should use type only on the last value, the one you interpolate
on.

On Friday, February 19, 2016, Steve Domin notifications@github.com wrote:

> @josevalim https://github.com/josevalim
> 
> def upcoming_events(group) do
>   now = Calendar.DateTime.now_utc |> Calecto.DateTimeUTC.cast  #now = Calendar.DateTime.now_utc |> Calendar.DateTime.to_micro_erl
>   from(g in Eager.Group,
>     join: e in assoc(g, :events),
>     where: e.group_id == ^group.id,
>     where: fragment("(?).wall_time > ?", type(e.start_datetime, :datetime), type(^now, :datetime)),    #where: fragment("(?).wall_time > ?", e.start_datetime, ^now),
>     select: e)end
> 
> # error*\* (Ecto.Query.CompileError) `type(e.start_datetime(), :datetime)` is not a valid query expression.
> - If you intended to call a database function, please check the documentation
>   for Ecto.Query to see the supported database expressions
> - If you intended to call an Elixir function or introduce a value,
>   you need to explicitly interpolate it with ^
> 
> Same error with Ecto.DateTime
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lau/calecto/issues/18#issuecomment-186199697.

## 

_José Valimwww.plataformatec.com.br
http://www.plataformatec.com.br/Founder and Director of R&D_

**Comment by stevedomin** [comment]
The following code is working:

``` elixir
def upcoming_events(group) do
  {:ok, now} = Calendar.DateTime.now_utc |> Calecto.DateTimeUTC.cast
  from(g in Eager.Group,
    join: e in assoc(g, :events),
    where: e.group_id == ^group.id,
    where: fragment("(?).wall_time > ?", e.start_datetime, type(^now, :datetime)),
    select: e)
end
```

which I simplified to:

``` elixir
def upcoming_events(group) do
  now = Calendar.DateTime.now_utc
  from(g in Eager.Group,
    join: e in assoc(g, :events),
    where: e.group_id == ^group.id,
    where: fragment("(?).wall_time > ?", e.start_datetime, type(^now, :datetime)),
    select: e)
end
```
